INSERT INTO blogful_articles (title, date_published, content) 
VALUES
	('Fish tricks', now() - '21 days'::INTERVAL, 'JUMPING THROUGH HOOPS'),
    ('Not Dogs', now() - '21 days'::INTERVAL, 'MANS LEST FRIEND'),
    ('Bluffalo Wings',now() - '21 days'::INTERVAL, 'TROUBLE IN UPSTATE ny'),
    ('Tofurkey', now() - '21 days'::INTERVAL, 'HEYO'),
    ('Pretenderloins',now() - '9 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Steak-believe', now() - '9 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Kale Seitan',now() - '9 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('NoBull Burger',now() - '9 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Turnip the Beet',now() - '9 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Mascarphony',now() - '7 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Burgatory',now() - '7 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Sleight of Ham',now() - '5 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Antichovies', now() - '5 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Lettuce B. Frank',now() - '5 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Pepperphony',now() - '5 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Shamburger',now() - '4 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Facon',now() - '4 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Salami-get-this-straight', now() - '4 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Mi-steak',now() - '3 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Ghost Beef',now() - '3 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Cheatloaf',now() - '3 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Fried Trickin', now() - '3 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Salmock',now() - '3 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Leaf Stroganoff',now() - '2 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Chicken Noodle Spoof',now() - '2 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Pep-parody Pizza',now() - '2 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Arti-fish-al pie',now() - '1 days'::INTERVAL, 'LOOK AT ALL THIS CONTENT'),
    ('Bolphony sandwiches',now(), 'LOOK AT ALL THIS CONTENT'),
    ('Chili non-carne', now(), 'LOOK AT ALL THIS CONTENT'),
    ('Don''t go bacon my heart', now(), 'LOOK AT ALL THIS CONTENT')
